### ISSUE TITLE
Docker start error

### ISSUE THREAD

**Issue by chenzhiguo** [Eugeny/tabby-connection-gateway#19]
Use the latest(now is 2023-10-29) version of TCG, there is error logs when start container.
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/app/tabby_connection_gateway/cli.py", line 7, in <module>
    from .admin_server import AdminServer
  File "/app/tabby_connection_gateway/admin_server.py", line 2, in <module>
    from tabby_connection_gateway.gateway_server import GatewayServer
  File "/app/tabby_connection_gateway/gateway_server.py", line 5, in <module>
    import websockets
  File "/usr/local/lib/python3.7/site-packages/websockets-12.0-py3.7.egg/websockets/__init__.py", line 6, in <module>
    from .version import version as __version__  # noqa: F401
  File "/usr/local/lib/python3.7/site-packages/websockets-12.0-py3.7.egg/websockets/version.py", line 3, in <module>
    import importlib.metadata
ModuleNotFoundError: No module named 'importlib.metadata'
```

**Comment by fixxolas** [comment]
+1

**Comment by alexdelprete** [comment]
Confirmed. :(

**Comment by slipperstree** [comment]
I solved this by：
1. Edit DockerFile, change 【FROM python:3.7-alpine ...】 to 【FROM python:3.8-alpine ...】
2. Build Docker image youself by command： 【docker build . -t my-tabby-gateway:latest】
3. Edit compose.yaml, change image from 【ghcr.io/eugeny/tabby-connection-gateway:latest】 to 【my-tabby-gateway:latest】  (note that you need also edit other settings in this file as well)
4. Start docker container by command: 【docker-compose up -d】

hope it helps

**Comment by SheperdHannigan** [comment]
> I solved this by：
> 
> 1. Edit DockerFile, change 【FROM python:3.7-alpine ...】 to 【FROM python:3.8-alpine ...】
> 2. Build Docker image youself by command： 【docker build . -t my-tabby-gateway:latest】
> 3. Edit compose.yaml, change image from 【ghcr.io/eugeny/tabby-connection-gateway:latest】 to 【my-tabby-gateway:latest】  (note that you need also edit other settings in this file as well)
> 4. Start docker container by command: 【docker-compose up -d】
> 
> hope it helps

I followed this instruction, and got these errors:
```

connection-gateway-1  | INFO:server:Token auth enabled
connection-gateway-1  | INFO:GatewayServer:Listening on 0.0.0.0:9000
connection-gateway-1  | Traceback (most recent call last):
connection-gateway-1  |   File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
connection-gateway-1  |     return _run_code(code, main_globals, None,
connection-gateway-1  |   File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
connection-gateway-1  |     exec(code, run_globals)
connection-gateway-1  |   File "/app/tabby_connection_gateway/cli.py", line 130, in <module>
connection-gateway-1  |     main()
connection-gateway-1  |   File "/app/tabby_connection_gateway/cli.py", line 122, in main
connection-gateway-1  |     asyncio.get_event_loop().run_until_complete(_main())
connection-gateway-1  |   File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
connection-gateway-1  |     return future.result()
connection-gateway-1  |   File "/app/tabby_connection_gateway/cli.py", line 105, in _main
connection-gateway-1  |     await GatewayServer(
connection-gateway-1  |   File "/app/tabby_connection_gateway/gateway_server.py", line 136, in start
connection-gateway-1  |     await super().start()
connection-gateway-1  |   File "/app/tabby_connection_gateway/base.py", line 23, in start
connection-gateway-1  |     await websockets.serve(
connection-gateway-1  |   File "/usr/local/lib/python3.8/site-packages/websockets-15.0.1-py3.8.egg/websockets/imports.py", line 78, in __getattr__
connection-gateway-1  |     return import_name(name, source, namespace)
connection-gateway-1  |   File "/usr/local/lib/python3.8/site-packages/websockets-15.0.1-py3.8.egg/websockets/imports.py", line 28, in import_name
connection-gateway-1  |     module = __import__(source[level:], namespace, None, [name], level)
connection-gateway-1  |   File "/usr/local/lib/python3.8/site-packages/websockets-15.0.1-py3.8.egg/websockets/asyncio/server.py", line 14, in <module>
connection-gateway-1  |     from ..exceptions import InvalidHeader
connection-gateway-1  |   File "/usr/local/lib/python3.8/site-packages/websockets-15.0.1-py3.8.egg/websockets/exceptions.py", line 461, in <module>
connection-gateway-1  |     from . import frames, http11  # noqa: E402
connection-gateway-1  |   File "/usr/local/lib/python3.8/site-packages/websockets-15.0.1-py3.8.egg/websockets/frames.py", line 430, in <module>
connection-gateway-1  |     from . import extensions  # noqa: E402
connection-gateway-1  |   File "/usr/local/lib/python3.8/site-packages/websockets-15.0.1-py3.8.egg/websockets/extensions/__init__.py", line 1, in <module>
connection-gateway-1  |     from .base import *
connection-gateway-1  |   File "/usr/local/lib/python3.8/site-packages/websockets-15.0.1-py3.8.egg/websockets/extensions/base.py", line 6, in <module>
connection-gateway-1  |     from ..typing import ExtensionName, ExtensionParameter
connection-gateway-1  |   File "/usr/local/lib/python3.8/site-packages/websockets-15.0.1-py3.8.egg/websockets/typing.py", line 59, in <module>
connection-gateway-1  |     ExtensionParameter = tuple[str, Optional[str]]
connection-gateway-1  | TypeError: 'type' object is not subscriptable
connection-gateway-1 exited with code 1
```

It seems that gateway has been not maintained anymore.
